language: ko

pipeline:
  - name: SpacyNLP
    model: "ko_core_news_sm"
  - name: custom_tokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  # - name: RegexEntityExtractor
  #   use_lookup_tables: True
  - name: DIETClassifier
    epochs: 100
  # - name: RegexEntityExtractor
  #   use_lookup_tables: True
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.65

policies:
  - name: TEDPolicy
    epochs: 100
  - name: AugmentedMemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.65
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: MappingPolicy